version: 2

sources:
   - name: raw
     database: SALES_ANALYTICS
     schema: RAW

     tables:
       - name: raw_carts
         columns:
         - name: load_timestamp
           tests: []

       - name: raw_cart_products